# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f51c2e786deb214993897d6c3b46d206fec269d711d8530592fa85040b25f8749d4cf3e5ea5bea9204eed8009b38e4e76e2e05c2b8a0d01d6cecdac265e2b989

test:
  secret_key_base: 737dc1b10df19f3059b90379829fbd514818e46f988f6501c6629b301f1485e807bf9fa9e71c26c79b63e7bec19a1c90968321b5abfd8fb6bbf2a5ca9c5c630c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
